version: '3.8'

services:
  service-cp-case-urn-mapper:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
        BASE_IMAGE: ${BASE_IMAGE}
        JAR_FILE_PATH: ${JAR_FILE_PATH}
        JAR_FILENAME: ${JAR_FILENAME}
    ports:
      - $SERVER_PORT:$SERVER_PORT
    networks:
      - service-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${SERVER_PORT}/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  service-network:
    name: service-cp-case-urn-mapper-network